MINIMA_ROMA:
  dataset:
#    modality: [ 'visible', 'infrared', 'depth', 'event', 'normal', 'sketch', 'paint' ]
    modality: [ 'visible', 'infrared', 'depth', 'normal' ]
#    modality: [ 'visible', 'infrared' ]

  train:
    lr_scale: 0.1
    train_resolution: 'medium' # 560,560
    n_nodes: 1
    n_gpus_per_node: 4
    batch_size: 3
    exp_name: 'minima_roma_outdoor'

  weight:
    pre_trained: true
    pre_trained_path: './weights/roma_outdoor.pth'
    resume_from_checkpoint: false # if true, resume from the last checkpoint in the exp_name folder